services:
  client:
    image: node:22-alpine
    container_name: pocketbase-client
    working_dir: /app
    volumes:
      - ./client:/app
      - ./pb_public:/pb_public
    command: sh -c "npm install && npm run build"
    restart: "no"

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv=PB_ENCRYPTION_KEY
      - --migrationsDir=/pb_migrations
      - --hooksDir=/pb_hooks
    environment:
      PB_ENCRYPTION_KEY: "" # optional
    ports:
      - "8090:8090"
    volumes:
      - /var/data/pocketbase/pb_data:/pb_data
      - ./pb_public:/pb_public
      - ./pb_migrations:/pb_migrations
      - ./pb_hooks:/pb_hooks
      # - /var/data/pocketbase/pb_migrations:/pb_migrations
    depends_on:
      client:
        condition: service_completed_successfully
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
  # swagger-ui:
  #   image: swaggerapi/swagger-ui
  #   container_name: pocketbase-swagger
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./swagger/openapi.yaml:/openapi.yaml:ro
  #   environment:
  #     SWAGGER_JSON: /openapi.yaml
  # caddy:
  #   image: caddy:latest
  #   container_name: caddy
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - /var/data/pocketbase/caddy_data:/data
  #     - /var/data/pocketbase/caddy_config:/config
  #   depends_on:
  #     - pocketbase
  #     - swagger-ui
